# -*- coding: utf-8 -*-
"""AI-Life-Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13l9N1sv3qG8CBSm39IMSpf8XjtWK2tk0
"""

# Install SWI-Prolog + pyswip
!apt update -qq &> /dev/null
!apt install swi-prolog -y -qq
!pip install pyswip -q

# Verify
!swipl --version
print("✅ SWI-Prolog & pyswip ready.")

# Commented out IPython magic to ensure Python compatibility.
# ===== CELL 2: PROLOG + ML SETUP =====
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from pyswip import Prolog
import matplotlib.pyplot as plt
import json

# Prolog KB - Enhanced for planner, procrastination, mental health
prolog_kb = """
# % Enhanced routine rules
healthy_sleep(22, 6).
healthy_study_range(9, 17).
healthy_meals(3).
exercise_min(30).

# % Study planner
optimal_study_time(H) :- healthy_study_range(Start, End), H >= Start, H < End.
avoid_procrastination(StudyH, ExMin, Meals) :- StudyH >= 3, ExMin >= 30, Meals >= 3.

# % Mental health analyzer
stress_risk(SleepH, StudyH, ExMin, SocialH) :-
    (SleepH < 6; StudyH > 8; ExMin < 15), SocialH < 1.
burnout_risk(StudyH, Breaks) :- StudyH > 6, Breaks < 2.
relaxation_score(SleepH, ExMin, SocialH, Score) :-
    Score is SleepH*1.5 + ExMin*0.1 + SocialH*2.

# % Personalized advice
get_advice(SleepH, StudyH, ExMin, SocialH, Advice) :-
    stress_risk(SleepH, StudyH, ExMin, SocialH), Advice = 'high stress';
    burnout_risk(StudyH, _), Advice = 'burnout risk';
    Advice = 'balanced'.
"""

with open('wellness.pl', 'w') as f: f.write(prolog_kb)
prolog = Prolog()
prolog.consult('wellness.pl')

# ML Models
data = {
    'sleep_h': [5,6,7,8,4,9,7,6,8,7,6,5,8],
    'study_h': [1,3,4,2,5,1,4,3,2,4,6,8,3],
    'ex_min': [10,30,45,20,0,60,45,30,20,45,30,10,50],
    'meals': [1,2,3,2,1,3,3,2,3,3,2,1,3],
    'social_h': [0,1,2,1,0,3,2,1,2,2,1,0,2],
    'breaks': [0,1,2,1,0,2,3,1,2,2,1,0,2],
    'wellness_score': [2,6,9,5,1,9,9,6,7,8,5,2,8]
}
df = pd.DataFrame(data)

X = df[['sleep_h','study_h','ex_min','meals','social_h','breaks']]
y = df['wellness_score']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
model = LinearRegression().fit(X_scaled, y)
print("✅ Prolog + ML Ready!")

# Commented out IPython magic to ensure Python compatibility.
# # ===== CELL 3: 🔥 STREAMLIT WEB INTERFACE =====
# %%writefile app.py
# import streamlit as st
# import numpy as np
# from pyswip import Prolog
# import matplotlib.pyplot as plt
# import io
# 
# # Load Prolog (in production, load from file)
# prolog = Prolog()
# prolog.consult('wellness.pl')
# 
# st.title("🚀 AI Life Assistant for Students")
# st.markdown("**Study Planner • Procrastination Detector • Mental Health Analyzer**")
# 
# # Sidebar inputs
# st.sidebar.header("📊 Your Daily Routine")
# sleep_s = st.sidebar.slider("Sleep Start", 0, 23, 22)
# sleep_e = st.sidebar.slider("Sleep End", 0, 23, 6)
# sleep_h = (sleep_e - sleep_s) % 24
# 
# study_h = st.sidebar.slider("Study Hours", 0, 10, 4)
# ex_min = st.sidebar.slider("Exercise (min)", 0, 120, 30)
# meals = st.sidebar.slider("Healthy Meals", 0, 5, 3)
# social_h = st.sidebar.slider("Social/Friends (hours)", 0, 5, 1)
# breaks = st.sidebar.slider("Study Breaks", 0, 5, 2)
# 
# if st.sidebar.button("🔥 ANALYZE MY ROUTINE"):
#     with st.spinner("AI analyzing..."):
#         # Prolog Analysis
#         st.subheader("🧠 Prolog AI Analysis")
# 
#         # Optimal study time
#         opt_study = list(prolog.query(f"optimal_study_time(14)"))  # Example afternoon slot
#         col1, col2, col3 = st.columns(3)
#         with col1:
#             procrastination = list(prolog.query(f"avoid_procrastination({study_h}, {ex_min}, {meals})"))
#             st.metric("Procrastination Risk", "✅ Low" if procrastination else "⚠️ High")
#         with col2:
#             stress_q = list(prolog.query(f"stress_risk({sleep_h}, {study_h}, {ex_min}, {social_h})"))
#             st.metric("Stress Level", "🔴 High" if stress_q else "🟢 Low")
#         with col3:
#             burnout_q = list(prolog.query(f"burnout_risk({study_h}, {breaks})"))
#             st.metric("Burnout Risk", "🔴 High" if burnout_q else "🟢 Low")
# 
#         # ML Wellness Score
#         st.subheader("📈 ML Wellness Score")
#         user_x = scaler.transform([[sleep_h, study_h, ex_min, meals, social_h, breaks]])
#         score = max(0, min(10, model.predict(user_x)[0]))
#         st.metric("Overall Wellness", f"{score:.1f}/10", delta=0.5)
# 
#         # Advice
#         advice_list = list(prolog.query(f"get_advice({sleep_h}, {study_h}, {ex_min}, {social_h}, Advice)"))
#         advice = advice_list[0]['Advice'] if advice_list else "balanced"
#         st.error("🚨 ACTION NEEDED!" if advice != "balanced" else "✅ You're good!")
#         st.write(f"**Prolog Diagnosis**: {advice.replace('high', 'HIGH PRIORITY').replace('risk', 'RISK')}")
# 
#         # Study Planner
#         st.subheader("📚 Smart Study Planner")
#         if procrastination:
#             st.success("🎉 Perfect balance - study 4-6 hrs with breaks!")
#         else:
#             st.warning("💡 Study in 9AM-5PM slots. Take 5-10 min breaks hourly.")
# 
#         # Visualization
#         fig, ax = plt.subplots(1,2, figsize=(12,5))
#         metrics = ['Sleep', 'Study', 'Exercise', 'Meals', 'Social', 'Breaks']
#         values = [sleep_h, study_h, ex_min/10, meals, social_h, breaks]
#         ax[0].bar(metrics, values, color='skyblue')
#         ax[0].set_title('Your Routine Balance')
#         ax[0].set_ylabel('Normalized Score')
# 
#         colors = ['green' if v > np.median(values) else 'red' for v in values]
#         ax[1].pie(values, labels=metrics, autopct='%1.1f%%', colors=colors)
#         ax[1].set_title('Routine Distribution')
#         st.pyplot(fig)
# 
# st.markdown("---")
# st.markdown("**Built with ❤️ for college students** | Prolog Logic + ML Prediction")

# ===== CELL 4: CLEAN INTERACTIVE DASHBOARD (GitHub Safe!) =====
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
import matplotlib.pyplot as plt
import numpy as np

print("🎉 AI Life Assistant - Interactive Dashboard")
print("=" * 50)

# Clean widgets (no saved state)
sleep_s = widgets.IntSlider(value=22, min=0, max=23, description='Sleep Start:')
sleep_e = widgets.IntSlider(value=6, min=0, max=23, description='Sleep End:')
study_h = widgets.FloatSlider(value=4.0, min=0, max=10, step=0.5, description='Study Hours:')
ex_min = widgets.IntSlider(value=30, min=0, max=120, description='Exercise:')
meals = widgets.IntSlider(value=3, min=0, max=5, description='Meals:')
social_h = widgets.IntSlider(value=1, min=0, max=5, description='Social:')
breaks = widgets.IntSlider(value=2, min=0, max=5, description='Breaks:')

analyze_btn = widgets.Button(description="🔥 ANALYZE ROUTINE", button_style='success')
output = widgets.Output()

def analyze(b):
    with output:
        clear_output(wait=True)
        sleep_total = (sleep_e.value - sleep_s.value) % 24

        print("📊 YOUR AI WELLNESS REPORT")
        print("━" * 40)

        # Prolog + ML Analysis
        proc_query = list(prolog.query(f"avoid_procrastination({study_h.value}, {ex_min.value}, {meals.value})"))
        stress_q = list(prolog.query(f"stress_risk({sleep_total}, {study_h.value}, {ex_min.value}, {social_h.value})"))
        burnout_q = list(prolog.query(f"burnout_risk({study_h.value}, {breaks.value})"))

        print(f"🎯 **Procrastination**: {'✅ LOW RISK' if proc_query else '⚠️ HIGH RISK'}")
        print(f"😰 **Stress Level**: {'🟢 LOW' if not stress_q else '🔴 HIGH'}")
        print(f"🔥 **Burnout Risk**: {'🟢 LOW' if not burnout_q else '🔴 HIGH'}")

        # ML Wellness Score
        user_data = np.array([[sleep_total, study_h.value, ex_min.value, meals.value, social_h.value, breaks.value]])
        user_scaled = scaler.transform(user_data)
        score = max(0, min(10, model.predict(user_scaled)[0]))
        stars = "⭐⭐⭐⭐⭐" if score>8 else "⭐⭐⭐⭐" if score>6 else "⭐⭐⭐" if score>4 else "⭐⭐"
        print(f"\n🏆 **AI WELLNESS SCORE**: {score:.1f}/10 {stars}")

        # Study Plan
        print("\n📚 **PERSONALIZED STUDY PLAN**")
        if proc_query and not stress_q and not burnout_q:
            print("   ✅ IDEAL ROUTINE: Study 9AM-5PM, 50min study + 10min breaks")
        else:
            print("   ⚠️  EMERGENCY FIX:")
            if study_h.value > 6: print("      • Split into 2hr sessions")
            if sleep_total < 6: print("      • Sleep 7-8hrs minimum")
            if ex_min.value < 20: print("      • 20min walk before study")

        # Charts
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4))
        metrics = ['Sleep\nhrs', 'Study\nhrs', 'Ex/10', 'Meals', 'Social\nhrs', 'Breaks']
        values = [sleep_total, study_h.value, ex_min.value/10, meals.value, social_h.value, breaks.value]
        colors = ['green' if v >= 1.5 else 'orange' if v >= 1 else 'red' for v in values]

        ax1.bar(metrics, values, color=colors, alpha=0.7)
        ax1.set_title('Routine Health Check', fontweight='bold')
        ax1.set_ylabel('Your Score')

        ax2.pie(values, labels=metrics, autopct='%1.1f%%', colors=colors)
        ax2.set_title('⚖️ Balance Distribution')
        plt.tight_layout()
        plt.show()

analyze_btn.on_click(analyze)

# Display (GitHub-safe)
display(HTML("<h2>🚀 AI Life Assistant</h2><p>Adjust sliders & click Analyze!</p>"))
display(widgets.VBox([
    widgets.HBox([sleep_s, sleep_e]),
    widgets.HBox([study_h, ex_min]),
    widgets.HBox([meals, social_h, breaks]),
    analyze_btn,
    output
]))

# ===== FIXED CELL 5: Auto-Clean Current Notebook =====
import json
from google.colab import files

# Get current notebook name automatically
notebook_name = !basename /proc/self/fd/0 2>/dev/null || echo "notebook.ipynb"
notebook_name = notebook_name[0].strip()

try:
    # Read current notebook content
    with open(notebook_name, 'r') as f:
        nb = json.load(f)

    # Clean ALL widget metadata
    for cell in nb['cells']:
        if 'metadata' in cell and 'widgets' in cell['metadata']:
            del cell['metadata']['widgets']

    clean_name = notebook_name.replace('.ipynb', '_clean.ipynb')
    with open(clean_name, 'w') as f:
        json.dump(nb, f, indent=1)

    print(f"✅ CLEAN '{clean_name}' saved!")
    print("📥 Download & upload to GitHub")
    files.download(clean_name)

except Exception as e:
    print("⚠️  Auto-clean failed (normal in Colab).")
    print("✅ Just: File → Download → .ipynb → GitHub")